version: '3.8'

services:
  backend:
    build: .
    ports:
      - "5000:5000"
    depends_on:
      - redis
    environment:
      - PORT=5000
      - NODE_ENV=production
      - REDIS_ENABLED=true
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      # Removed the Redis password environment variable
    env_file:
      - .env
    restart: unless-stopped

  redis:
    image: redis:alpine
    # Removed the password requirement command
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    restart: unless-stopped

volumes:
  redis-data: